- id: '1527058589641'
  alias: 开关
  trigger:
  - entity_id: switch.mi_socket_plus
    from: turn_off
    platform: state
    to: turn_off
  condition: []
  action:
  - data:
      payload: I folowwo you
      topic: socket
    service: mqtt.publish
- id: '1527058706033'
  alias: socket
  trigger:
  - entity_id: switch.mi_socket_plus
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      payload: waa
      topic: socket
    service: mqtt.publish
#- id: '1527060957095'
#  alias: unavailable
#  trigger:
#  - entity_id: switch.mi_socket_plus
#    from: 'on'
#    platform: state
#    to: unavailable
#  - entity_id: switch.mi_socket_plus
#    from: 'off'
#    platform: state
#    to: unavailable
#  condition: []
#  action:
#  - service: homeassistant.restart
