/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_het_protocol_CProtocolManager */

#ifndef _Included_com_het_protocol_CProtocolManager
#define _Included_com_het_protocol_CProtocolManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_het_protocol_CProtocolManager
 * Method:    parseData
 * Signature: (Lcom/com/het/udp/wifi/model/PacketModel;)Lcom/com/het/udp/wifi/model/PacketModel;
 */
JNIEXPORT jobject JNICALL Java_com_het_protocol_CProtocolManager_parseData
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_het_protocol_CProtocolManager
 * Method:    packageData
 * Signature: (Lcom/com/het/udp/wifi/model/PacketModel;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_het_protocol_CProtocolManager_packageData
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
