#!/bin/bash


function startFrp(){
  readLog
  ./frpcerver stop
  ./frpcerver start

readLog
}


function stopFrp(){
  ./frpcerver stop

  readLog
}
function checkFrp(){
  ps aux | grep 'frp'
}

function readLog(){
 cat log.log
}

function delLog(){
rm -rf log.log
}


echo "1.启动frp"
echo "2.停止frp"
echo "3.查看frp状态"
echo "4.查看日志"
echo "5.删除日志"
echo "******Enter nothing to exit*****"
read num

case "$num" in
[1] ) (startFrp);;
[2] ) (stopFrp);;
[3] ) (checkFrp);;
[4] ) (readLog);;
[5] ) (delLog);;

*) echo "nothing,exit";;
esac
