#!/bin/sh
#
# Startup script for the Keepalived daemon
#
# processname: keepalived
# pidfile: /var/run/keepalived.pid
# config: /etc/keepalived/keepalived.conf
# chkconfig: - 21 79 #此处必须有，是chkconfig服务注册到linux启动级别的配置
# description: Start and stop Keepalived

SERVER=/home/frp/frp_0.19.1_linux_386
cd $SERVER

case "$1" in

  start)
    nohup ./frps -c ./frps.ini > $SERVER/log.log &
    echo $! > $SERVER/pid.pid
    ;;

  stop)
    kill `cat $SERVER/pid.pid`
    rm -rf $SERVER/pid.pid
    ;;

  restart)
    $0 stop
    sleep 1
    $0 start
    ;;

  *)
    echo "Usage: run.sh {start|stop|restart}"
    ;;

esac

exit 0
